name: Build Linux App

on:
  workflow_dispatch:  # Permite ejecutar manualmente
    inputs:
      upload_artifacts:
        description: 'Subir artefactos (consume espacio de almacenamiento)'
        required: false
        default: false
        type: boolean
  push:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Instalar dependencias
      working-directory: frontend
      run: npm install
      
    - name: Construir para Linux
      working-directory: frontend
      env:
        CI: false
        ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
      run: npm run electron-build-ci -- --linux
      
    - name: Listar archivos generados
      working-directory: frontend
      run: |
        echo "Archivos generados:"
        ls -la dist/
        echo "Tamaños de archivos:"
        du -h dist/*
      
    - name: Subir artefactos Linux (solo si se solicita)
      if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.upload_artifacts == 'true') || github.event_name == 'release' }}
      uses: actions/upload-artifact@v4
      with:
        name: linux-packages-${{ github.run_number }}
        path: |
          frontend/dist/*.rpm
          frontend/dist/*.deb
          frontend/dist/*.AppImage
        retention-days: 7  # Solo mantener por 7 días para ahorrar espacio 