name: Build Linux App

on:
  workflow_dispatch:  # Permite ejecutar manualmente
  push:
    branches: [ main, master ]  # Ajustado para main o master
  pull_request:
    branches: [ main, master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Instalar dependencias del frontend
      working-directory: frontend
      run: npm ci
      
    - name: Construir aplicación React
      working-directory: frontend
      run: npm run build
      
    - name: Construir para Linux
      working-directory: frontend
      run: npm run electron-build -- --linux
      
    - name: Listar archivos generados
      working-directory: frontend
      run: ls -la dist/
      
    - name: Subir artefactos Linux
      uses: actions/upload-artifact@v4
      with:
        name: linux-packages
        path: |
          frontend/dist/*.rpm
          frontend/dist/*.deb
          frontend/dist/*.AppImage 