name: Emergency Artifact Cleanup

on:
  workflow_dispatch:

jobs:
  emergency-cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    
    steps:
    - name: Emergency cleanup - Delete ALL artifacts
      uses: actions/github-script@v7
      with:
        script: |
          const artifacts = await github.rest.actions.listArtifactsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 100
          });
          
          console.log(`🚨 Deleting ${artifacts.data.artifacts.length} artifacts`);
          
          let deletedCount = 0;
          let freedSpace = 0;
          
          for (const artifact of artifacts.data.artifacts) {
            try {
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id
              });
              deletedCount++;
              freedSpace += artifact.size_in_bytes;
              console.log(`✅ Deleted: ${artifact.name}`);
            } catch (error) {
              console.error(`❌ Failed: ${artifact.name}`);
            }
          }
          
          const freedSpaceMB = (freedSpace / (1024 * 1024)).toFixed(2);
          console.log(`🎉 Deleted ${deletedCount} artifacts, freed ${freedSpaceMB} MB`);
